decouple.UndefinedValueError: DATABASE_URL not found. Declare it as envvar or define a default value.

[2025-01-12 22:10:41 +0000] [4] [INFO] Worker exiting (pid: 4)

[2025-01-12 22:10:41 +0000] [1] [ERROR] Worker (pid:4) exited with code 3

[2025-01-12 22:10:41 +0000] [1] [ERROR] Shutting down: Master

[2025-01-12 22:10:41 +0000] [1] [ERROR] Reason: Worker failed to boot.

  File "/opt/venv/lib/python3.12/site-packages/decouple.py", line 248, in __call__

Carregando .env do caminho: /app

    return self.config(*args, **kwargs)

DATABASE_URL: NÃ£o encontrado

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[2025-01-12 22:10:43 +0000] [4] [ERROR] Exception in worker process

  File "/opt/venv/lib/python3.12/site-packages/decouple.py", line 107, in __call__

    return self.get(*args, **kwargs)

Traceback (most recent call last):

           ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker

  File "/opt/venv/lib/python3.12/site-packages/decouple.py", line 92, in get

    worker.init_process()

    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))

  File "/opt/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process

decouple.UndefinedValueError: DATABASE_URL not found. Declare it as envvar or define a default value.

    self.load_wsgi()

[2025-01-12 22:10:43 +0000] [4] [INFO] Worker exiting (pid: 4)

  File "/opt/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi

    self.wsgi = self.app.wsgi()

                ^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi

[2025-01-12 22:10:43 +0000] [1] [ERROR] Worker (pid:4) exited with code 3

    self.callable = self.load()

[2025-01-12 22:10:43 +0000] [1] [ERROR] Shutting down: Master

                    ^^^^^^^^^^^

[2025-01-12 22:10:43 +0000] [1] [ERROR] Reason: Worker failed to boot.

  File "/opt/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load

    return self.load_wsgiapp()

           ^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp

    return util.import_app(self.app_uri)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app

    mod = importlib.import_module(module)

          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/root/.nix-profile/lib/python3.12/importlib/__init__.py", line 90, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 995, in exec_module

  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed

  File "/app/Albino_Marks/wsgi.py", line 16, in <module>

    application = get_wsgi_application()

                  ^^^^^^^^^^^^^^^^^^^^^^


Pr_Albino_Marks | Railway
5:10pm